name: Yarn Build, NPM and github pages deploy

on:
  release:
    types: [published]
  workflow_dispatch:

run-name: ${{ github.actor }} 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.13.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
        shell: bash

      - name: Build
        run: yarn build
        shell: bash

      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_PUBLISH }}" > ~/.npmrc

      - name: Publish npm
        run: npm publish --access public
